language: python
python:
  - 2.6
install: pip install tox
# List envs explicitly to skip PyPy
script: tox -e py27,py26,py25,no-glob2,external-jsmin,external-rjsmin
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master

