language: python
python:
  - 2.6
install: pip install tox
before_install:
   - sudo apt-get install zlib1g-dev
script: tox
notifications:
  email:
    - michael@elsdoerfer.com
branches:
  only:
    - master

